export const dataTeam1 = [
  { id: 1, name: "Zakkle", alive: true, score: "356", kill: "23", death: "11" },
  { id: 2, name: "Atal", alive: false, score: "320", kill: "20", death: "14" },
  { id: 3, name: "Callet", alive: true, score: "311", kill: "20", death: "11" },
  {
    id: 4,
    name: "Simiell",
    alive: false,
    score: "304",
    kill: "19",
    death: "11",
  },
  { id: 5, name: "Lspe", alive: true, score: "298", kill: "19", death: "11" },
  { id: 6, name: "Ggier", alive: true, score: "296", kill: "20", death: "11" },
  { id: 7, name: "Jieann", alive: true, score: "288", kill: "18", death: "11" },
  {
    id: 8,
    name: "Iorale",
    alive: false,
    score: "284",
    kill: "17",
    death: "11",
  },
  { id: 9, name: "Yanna", alive: true, score: "282", kill: "19", death: "11" },
  { id: 10, name: "Samu", alive: true, score: "272", kill: "20", death: "11" },
  {
    id: 11,
    name: "Zzyaako",
    alive: false,
    score: "270",
    kill: "17",
    death: "11",
  },
  { id: 12, name: "Liant", alive: true, score: "268", kill: "12", death: "11" },
  {
    id: 13,
    name: "Ooksane",
    alive: true,
    score: "266",
    kill: "16",
    death: "11",
  },
  {
    id: 14,
    name: "Tonyack",
    alive: false,
    score: "260",
    kill: "18",
    death: "11",
  },
  { id: 15, name: "Yann", alive: true, score: "252", kill: "17", death: "11" },
  { id: 16, name: "Ramin", alive: true, score: "222", kill: "17", death: "11" },
  {
    id: 17,
    name: "Warrie",
    alive: true,
    score: "216",
    kill: "17",
    death: "11",
  },
  {
    id: 18,
    name: "Topati",
    alive: true,
    score: "202",
    kill: "16",
    death: "11",
  },
  {
    id: 19,
    name: "Juleigh",
    alive: true,
    score: "198",
    kill: "16",
    death: "11",
  },
  {
    id: 20,
    name: "Rietta",
    alive: false,
    score: "198",
    kill: "15",
    death: "11",
  },
  { id: 21, name: "Toni", alive: true, score: "186", kill: "17", death: "11" },
  {
    id: 22,
    name: "Welchan",
    alive: true,
    score: "184",
    kill: "17",
    death: "11",
  },
  { id: 23, name: "Zwill", alive: true, score: "180", kill: "16", death: "11" },
  { id: 24, name: "Zule", alive: true, score: "166", kill: "16", death: "11" },
  {
    id: 25,
    name: "Montenix",
    alive: false,
    score: "162",
    kill: "16",
    death: "11",
  },
  {
    id: 26,
    name: "Gailia",
    alive: true,
    score: "160",
    kill: "16",
    death: "11",
  },
  { id: 27, name: "Zaid", alive: true, score: "156", kill: "15", death: "11" },
  {
    id: 28,
    name: "Hercean",
    alive: true,
    score: "154",
    kill: "15",
    death: "11",
  },
  { id: 29, name: "Berty", alive: true, score: "152", kill: "15", death: "11" },
  { id: 30, name: "Mill", alive: true, score: "152", kill: "14", death: "11" },
  { id: 31, name: "Lana", alive: false, score: "150", kill: "12", death: "11" },
  { id: 32, name: "Sasia", alive: true, score: "144", kill: "12", death: "11" },
  {
    id: 33,
    name: "Ewandarv",
    alive: false,
    score: "86",
    kill: "13",
    death: "11",
  },
  { id: 34, name: "Osal", alive: true, score: "74", kill: "11", death: "11" },
  { id: 35, name: "Peigh", alive: true, score: "66", kill: "7", death: "11" },
  { id: 36, name: "Josh", alive: true, score: "66", kill: "6", death: "11" },
  { id: 37, name: "Ackier", alive: true, score: "54", kill: "8", death: "11" },
  { id: 38, name: "Ikore", alive: true, score: "54", kill: "9", death: "11" },
  { id: 39, name: "Xanthel", alive: true, score: "48", kill: "2", death: "11" },
  { id: 40, name: "Floret", alive: true, score: "46", kill: "5", death: "11" },
  {
    id: 41,
    name: "Heremili",
    alive: true,
    score: "44",
    kill: "4",
    death: "11",
  },
  { id: 42, name: "Jakei", alive: false, score: "42", kill: "6", death: "11" },
  {
    id: 43,
    name: "Montina",
    alive: false,
    score: "40",
    kill: "2",
    death: "11",
  },
  { id: 44, name: "Zizio", alive: false, score: "28", kill: "3", death: "11" },
  { id: 45, name: "Qamran", alive: false, score: "28", kill: "2", death: "11" },
  { id: 46, name: "Perist", alive: false, score: "24", kill: "3", death: "11" },
  { id: 47, name: "Victorg", alive: false, score: "8", kill: "2", death: "11" },
  { id: 48, name: "Orenet", alive: false, score: "6", kill: "1", death: "11" },
  { id: 49, name: "Cachump", alive: false, score: "4", kill: "0", death: "11" },
  { id: 50, name: "Wend", alive: false, score: "0", kill: "0", death: "11" },
];

export const dataTeam2 = [
  {
    id: 51,
    name: "Thomas",
    alive: true,
    score: "360",
    kill: "23",
    death: "11",
  },
  { id: 52, name: "Jim", alive: false, score: "330", kill: "22", death: "14" },
  { id: 53, name: "Matt", alive: true, score: "300", kill: "20", death: "11" },
  {
    id: 54,
    name: "Sami",
    alive: false,
    score: "278",
    kill: "19",
    death: "11",
  },
  { id: 55, name: "Joey", alive: false, score: "298", kill: "16", death: "11" },
  { id: 56, name: "Josh", alive: true, score: "244", kill: "16", death: "11" },
  { id: 57, name: "Dan", alive: false, score: "240", kill: "13", death: "11" },
  {
    id: 58,
    name: "Miller",
    alive: false,
    score: "266",
    kill: "17",
    death: "11",
  },
  {
    id: 59,
    name: "Benji",
    alive: false,
    score: "242",
    kill: "19",
    death: "11",
  },
  { id: 60, name: "Luke", alive: false, score: "234", kill: "16", death: "11" },
  {
    id: 61,
    name: "White",
    alive: false,
    score: "242",
    kill: "17",
    death: "11",
  },
  {
    id: 62,
    name: "Robocop",
    alive: true,
    score: "222",
    kill: "12",
    death: "11",
  },
  {
    id: 63,
    name: "Moore",
    alive: false,
    score: "222",
    kill: "16",
    death: "11",
  },
  {
    id: 64,
    name: "TonyaHook",
    alive: false,
    score: "212",
    kill: "18",
    death: "11",
  },
  { id: 65, name: "Yann", alive: true, score: "224", kill: "17", death: "11" },
  { id: 66, name: "Ramin", alive: true, score: "222", kill: "17", death: "11" },
  {
    id: 67,
    name: "Larrie",
    alive: true,
    score: "144",
    kill: "17",
    death: "11",
  },
  {
    id: 68,
    name: "Topatych",
    alive: true,
    score: "144",
    kill: "16",
    death: "11",
  },
  {
    id: 69,
    name: "Pim",
    alive: true,
    score: "142",
    kill: "16",
    death: "11",
  },
  {
    id: 70,
    name: "Thomas",
    alive: false,
    score: "142",
    kill: "15",
    death: "11",
  },
  { id: 71, name: "Toni", alive: true, score: "140", kill: "17", death: "11" },
  {
    id: 72,
    name: "Marty",
    alive: true,
    score: "88",
    kill: "17",
    death: "11",
  },
  { id: 73, name: "Zwill", alive: true, score: "86", kill: "16", death: "11" },
  { id: 74, name: "Zule", alive: true, score: "86", kill: "16", death: "11" },
  {
    id: 75,
    name: "Ilya",
    alive: false,
    score: "84",
    kill: "16",
    death: "11",
  },
  {
    id: 76,
    name: "Stoma",
    alive: true,
    score: "84",
    kill: "16",
    death: "11",
  },
  { id: 7, name: "Zaid", alive: true, score: "80", kill: "15", death: "11" },
  {
    id: 78,
    name: "Dai",
    alive: true,
    score: "72",
    kill: "15",
    death: "11",
  },
  { id: 79, name: "Chris", alive: true, score: "72", kill: "15", death: "11" },
  {
    id: 80,
    name: "Andres",
    alive: true,
    score: "70",
    kill: "14",
    death: "11",
  },
  {
    id: 81,
    name: "Mickey",
    alive: false,
    score: "70",
    kill: "12",
    death: "11",
  },
  {
    id: 82,
    name: "Bradd",
    alive: false,
    score: "44",
    kill: "12",
    death: "11",
  },
  {
    id: 83,
    name: "Ewandarv",
    alive: false,
    score: "44",
    kill: "13",
    death: "11",
  },
  {
    id: 84,
    name: "Bobbie",
    alive: false,
    score: "42",
    kill: "11",
    death: "11",
  },
  { id: 85, name: "Peigh", alive: false, score: "40", kill: "7", death: "11" },
  { id: 86, name: "Evans", alive: false, score: "40", kill: "6", death: "11" },
  { id: 87, name: "Kye", alive: true, score: "40", kill: "8", death: "11" },
  { id: 88, name: "Ikore", alive: false, score: "40", kill: "9", death: "11" },
  {
    id: 89,
    name: "Phillips",
    alive: true,
    score: "22",
    kill: "2",
    death: "11",
  },
  { id: 90, name: "Sanchez", alive: true, score: "20", kill: "5", death: "11" },
  {
    id: 91,
    name: "Heremili",
    alive: true,
    score: "20",
    kill: "4",
    death: "11",
  },
  { id: 92, name: "Jakei", alive: false, score: "12", kill: "6", death: "11" },
  {
    id: 93,
    name: "Montina",
    alive: false,
    score: "10",
    kill: "2",
    death: "11",
  },
  { id: 94, name: "Zizio", alive: false, score: "8", kill: "0", death: "15" },
  { id: 95, name: "Jon", alive: false, score: "6", kill: "0", death: "18" },
  { id: 96, name: "Scott", alive: false, score: "2", kill: "0", death: "17" },
  { id: 97, name: "Lopez", alive: false, score: "2", kill: "0", death: "16" },
  { id: 98, name: "Chris", alive: false, score: "2", kill: "0", death: "21" },
  { id: 99, name: "Adams", alive: false, score: "2", kill: "0", death: "21" },
  { id: 100, name: "Walker", alive: false, score: "0", kill: "0", death: "22" },
];
